import { readFileSync } from "node:fs";
import { join } from "node:path";

import { sql } from "drizzle-orm";
import { readMigrationFiles } from "drizzle-orm/migrator";
import { afterAll, beforeAll, describe, expect, test, vi } from "vitest";

import { withActor, withSystem } from "./actor";
import { migrationConfig } from "./migrate";
import { createTestDatabase } from "./test/harness";

type Row = Record<string, unknown>;

let harness: Awaited<ReturnType<typeof createTestDatabase>>;
let ownerRole: string;

const ACTOR = "018f5e7a-1c2b-7d3e-9a4f-5b6c7d8e9f01";

function rows(result: unknown): Row[] {
  return (result as { rows: Row[] }).rows;
}

beforeAll(async () => {
  harness = await createTestDatabase();
  const [row] = rows(await harness.db.execute(sql`select current_user as owner`));
  ownerRole = row?.owner as string;
});

afterAll(async () => {
  await harness.close();
});

describe("the committed journal", () => {
  test("is applied by the harness and recorded in the migrations table", async () => {
    const journal = JSON.parse(
      readFileSync(join(migrationConfig.migrationsFolder, "meta", "_journal.json"), "utf8"),
    ) as { entries: { tag: string; when: number }[] };
    const files = readMigrationFiles(migrationConfig);
    expect(journal.entries[0]?.tag).toBe("0000_create_app_role");

    const applied = rows(
      await harness.db.execute(
        sql`select hash, created_at from drizzle.__drizzle_migrations order by created_at`,
      ),
    );
    expect(applied).toHaveLength(files.length);
    expect(applied[0]?.hash).toBe(files[0]?.hash);
    expect(Number(applied[0]?.created_at)).toBe(journal.entries[0]?.when);
  });

  test("creates tidefern_app without login, inheritance or RLS bypass", async () => {
    const [role] = rows(
      await harness.db.execute(
        sql`select rolcanlogin, rolinherit, rolbypassrls, rolsuper from pg_catalog.pg_roles where rolname = 'tidefern_app'`,
      ),
    );
    expect(role).toEqual({
      rolcanlogin: false,
      rolinherit: false,
      rolbypassrls: false,
      rolsuper: false,
    });
  });

  test("grants the migrating role SET on tidefern_app", async () => {
    const [membership] = rows(
      await harness.db.execute(
        sql`select set_option from pg_catalog.pg_auth_members where roleid = 'tidefern_app'::regrole and member = current_user::regrole`,
      ),
    );
    expect(membership).toEqual({ set_option: true });
  });
});

describe("withActor", () => {
  test("runs as tidefern_app with the actor id set for the transaction", async () => {
    const [inside] = await withActor(
      ACTOR,
      async (tx) =>
        rows(
          await tx.execute(
            sql`select current_user as role, current_setting('app.actor_id', true) as actor`,
          ),
        ),
      harness.db,
    );
    expect(inside).toEqual({ role: "tidefern_app", actor: ACTOR });
  });

  test("leaves no role or setting behind once the transaction ends", async () => {
    await withActor(ACTOR, async () => undefined, harness.db);
    const [after] = rows(
      await harness.db.execute(
        sql`select current_user as role, coalesce(current_setting('app.actor_id', true), '') as actor`,
      ),
    );
    expect(after).toEqual({ role: ownerRole, actor: "" });
  });

  test("rejects an actor id that is not a UUID before touching the database", async () => {
    const fn = vi.fn(async () => "reached");
    await expect(withActor("owner", fn, harness.db)).rejects.toThrow(TypeError);
    await expect(withActor("", fn, harness.db)).rejects.toThrow(TypeError);
    expect(fn).not.toHaveBeenCalled();
  });

  test("can read and write a table created after the migration without a new grant", async () => {
    await harness.db.execute(
      sql`create table later_rows (id integer generated by default as identity primary key, label text not null)`,
    );
    await harness.db.execute(sql`insert into later_rows (label) values ('first')`);

    const count = await withActor(
      ACTOR,
      async (tx) => {
        await tx.execute(sql`insert into later_rows (label) values ('second')`);
        const [row] = rows(await tx.execute(sql`select count(*)::int as total from later_rows`));
        return row?.total;
      },
      harness.db,
    );
    expect(count).toBe(2);

    const [committed] = rows(
      await harness.db.execute(sql`select count(*)::int as total from later_rows`),
    );
    expect(committed?.total).toBe(2);
  });
});

describe("withSystem", () => {
  test("turns app.system on for the transaction and keeps the connection role", async () => {
    const [inside] = await withSystem(
      async (tx) =>
        rows(
          await tx.execute(
            sql`select current_user as role, current_setting('app.system', true) as system`,
          ),
        ),
      harness.db,
    );
    expect(inside).toEqual({ role: ownerRole, system: "on" });

    const [after] = rows(
      await harness.db.execute(
        sql`select coalesce(current_setting('app.system', true), '') as system`,
      ),
    );
    expect(after?.system).toBe("");
  });
});
