// The identity tables are generated by the Better Auth CLI (task C1):
// `pnpm --filter @tidefern/auth generate` rewrites ../auth-schema.ts, and
// drizzle-kit turns the whole of this module into migrations. The other
// areas of architecture record 7.4 follow, one file each, in the order
// their migrations were generated.
export * from "../auth-schema";
export * from "./enums";
export * from "./profiles";
export * from "./keys";
export * from "./relationships";
export * from "./cycle";
export * from "./pregnancy";
export * from "./children";
