// The identity tables are generated by the Better Auth CLI (task C1):
// `pnpm --filter @tidefern/auth generate` rewrites ../auth-schema.ts, and
// drizzle-kit turns the whole of this module into migrations. Tables for
// the other areas of architecture record 7.4 arrive with tasks B3 to B7.
export * from "../auth-schema";
export * from "./enums";
export * from "./profiles";
export * from "./keys";
