// Tables arrive with tasks B2 to B7. The module stays importable so
// drizzle-kit and the client have a schema object from the first migration on.
// The identity tables are generated by the Better Auth CLI (task C1):
// `pnpm --filter @tidefern/auth generate` rewrites ../auth-schema.ts, and
// task B2 turns it into a migration.
export * from "../auth-schema";
